## Copyright © 2020, Oracle and/or its affiliates. 
## All rights reserved. The Universal Permissive License (UPL), Version 1.0 as shown at http://oss.oracle.com/licenses/upl

    title: "Create ADW and OAC in Oracle Cloud Infrastructure"
    stackDescription: "Deploy Autonomous Data Warehouse (ADW) and Oracle Analytics Cloud (OAC) in Oracle Cloud Infrastructure."
    schemaVersion: 1.1.0
    version: "20190404"
    locale: "en"

    variableGroups:
    - title: General Configuration
      visible: false
      variables:
      - tenancy_ocid

    - title: Required Configuration
      visible: true  
      variables:
      - compartment_ocid
      - region
      - autonomous_database_admin_password
      - analytics_instance_idcs_access_token

    - title: Optional Configuration
      visible: true
      variables:      
      - autonomous_database_cpu_core_count
      - autonomous_database_db_name
      - autonomous_database_display_name 
      - autonomous_database_db_version
      - autonomous_database_is_auto_scaling_enabled
      - autonomous_database_data_storage_size_in_tbs
      - autonomous_database_db_workload
      - autonomous_database_license_model
      - autonomous_database_data_safe_status
      - autonomous_database_whitelisted_ips
      - analytics_instance_capacity_capacity_type
      - analytics_instance_capacity_capacity_value
      - analytics_instance_feature_set
      - analytics_instance_license_type
      - analytics_instance_name

    
    variables:

      compartment_ocid:
        type: oci:identity:compartment:id
        required: true
        visibile: true
        title: Compartment
        description: "Compartment where you want to create the solution resources"

      region:
        type: oci:identity:region:name
        required: true
        visibile: true
        title: Region
        description: "Region where you want to deploy the resources defined by this stack."

      autonomous_database_admin_password:
        type: password
        required: true
        title: "ADW Database Password"
        description: "ADW Database Password for ADMIN user."

      analytics_instance_idcs_access_token:
        type: text
        required: true
        title: "IDCS Acccess Token for OAC"
        description: "IDCS Acccess Token required by Oracle Analytics Cloud (OAC)."

      # Optional Configuration

      autonomous_database_cpu_core_count:
        type: string
        default: "1"
        visible: true
        required: false
        title: "ADW database CPU core count"
        description: "Autonomous Data Warehouse (ADW) CPU core count"

      autonomous_database_db_name:
        type: string
        default: "aTFdb"
        visible: true
        required: false
        title: "ADW database name"
        description: "Autonomous Data Warehouse (ADW) Database name"

      autonomous_database_display_name:
        type: string
        default: "My ATP DB"
        visible: true
        required: false
        title: "ADW database display name"
        description: "Autonomous Data Warehouse (ADW) Database display name"

      autonomous_database_db_version: 
        type: string
        default: "19c"
        visible: true
        required: false
        title: "ADW database version"
        description: "Autonomous Data Warehouse (ADW) Database version"

      autonomous_database_is_auto_scaling_enabled: 
        type: boolean
        default: false 
        visible: true
        required: false
        title: "ADW database auto-scalling enabled"
        description: "Autonomous Data Warehouse (ADW) auto-scalling enabled"

      autonomous_database_data_storage_size_in_tbs: 
        type: string
        default: "1"
        visible: true
        required: false
        title: "ADW database data storage size in TBs"
        description: "Autonomous Data Warehouse (ADW) data storage size in terabytes."

      autonomous_database_db_workload: 
        type: string
        default: "DW"
        visible: true
        required: false
        title: "ADW database data workload"
        description: "Autonomous Data Warehouse (ADW) workload."

      autonomous_database_license_model:
        type: string
        default: "BRING_YOUR_OWN_LICENSE"
        visible: true
        required: false
        title: "ADW databaselicense model"
        description: "Autonomous Data Warehouse (ADW) license model."

      autonomous_database_data_safe_status:
        type: string
        default: "NOT_REGISTERED" 
        visible: true
        required: false
        title: "ADW database DataSafe status"
        description: "Autonomous Data Warehouse (ADW) DataSafe status."

      autonomous_database_whitelisted_ips:
        type: string
        default: '["240.0.0.0/4"]'
        visible: true
        required: false
        title: "ADW database whitelisted IPs"
        description: "Autonomous Data Warehouse (ADW) whitelisted IPs."

      analytics_instance_capacity_capacity_type:
        type: string
        default: "OLPU_COUNT"
        visible: true
        required: false
        title: "OAC instance capacity type"
        description: "Oracle Analytics Cloud (OAC) instance capacity type"

      analytics_instance_feature_set: 
        type: string
        default: "ENTERPRISE_ANALYTICS"
        visible: true
        required: false
        title: "OAC instance feature set"
        description: "Oracle Analytics Cloud (OAC) instance feature set"

      analytics_instance_license_type: 
        type: string
        default: "LICENSE_INCLUDED"
        visible: true
        required: false
        title: "OAC instance license_type"
        description: "Oracle Analytics Cloud (OAC) instance license_type"

      analytics_instance_name:
        type: string
        default: "OAC"
        visible: true
        required: false
        title: "OAC instance name"
        description: "Oracle Analytics Cloud (OAC) instance name"


